### PR TITLE
The version number was fixed.

### PR DESCRIPTION
**Pull request by 3kami3**
The plugin version number of Redmine was fixed.
0.1.3 -> 0.2.0

### CODE REVIEW

**Comment by 3kami3** [comment]
Thank you Merge.
@phlegx Please re-tag the tag again.

**Comment by phlegx** [comment]
Already done! See here [tag/v0.2.0](phlegx/redmine_gitlab_hook/releases/tag/v0.2.0)

**Comment by 3kami3** [comment]
Really?
@phlegx Why is this?
<pre>
$ git clone https://github.com/phlegx/redmine_gitlab_hook.git
Cloning into 'redmine_gitlab_hook'...
remote: Counting objects: 151, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 151 (delta 0), reused 1 (delta 0), pack-reused 146
Receiving objects: 100% (151/151), 26.90 KiB | 0 bytes/s, done.
Resolving deltas: 100% (46/46), done.

$ cd redmine_gitlab_hook/

$ git checkout refs/tags/v0.2.0
Note: checking out 'refs/tags/v0.2.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at dd60f35... Merge pull request #36 from jcppkkk/master

$ git log --oneline | head -3
dd60f35 Merge pull request #36 from jcppkkk/master
719b353 Revise for phlegx/redmine_gitlab_hook#36, raise error when git clone fails
4a7ba60 Support multiple repositories in same redmine project

$ grep version init.rb
  version '0.1.3'
  requires_redmine :version_or_higher => '2.3.0'
</pre>

**Comment by phlegx** [comment]
Found the problem: https://www.abeautifulsite.net/how-to-delete-a-tag-on-github
Release is now ok.

**Pull request merged**
